# fly.toml app configuration file generated for sbobine-notify on 2024-10-12T23:43:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sbobine-notify'
primary_region = 'fra'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="my_app_data"
  destination="/data"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
